from .posts import Post as Post
from _typeshed import Incomplete
from pathlib import Path

logger: Incomplete
formatter: Incomplete
handler: Incomplete

class Client:
    API_KEY: Incomplete
    USER_ID: Incomplete
    def __init__(self, api_key: str, user_id: str) -> None: ...
    def list_posts(self, tags: str | set[str], limit: int = 1000, pid: int | None = None) -> list[Post]: ...
    def get_post(self, post_id: int) -> Post: ...
    def download_post(self, post: Post, destination: Path, file_name: str | None = None, file_url: str | None = None) -> None: ...
    def list_posts_from_pool(self, pool_id: int) -> list[Post]: ...
    def list_posts_from_favorites(self, user: int) -> list[Post]: ...
    def list_post_ids_from_pool(self, pool_id: int) -> list[int]: ...
    def list_post_ids_from_favorites(self, user: int) -> list[int]: ...
